### ISSUE TITLE
StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by ImeshaDilshani** [ImeshaDilshani/JavaInAction#2]
```
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: Range [16, 15) out of bounds for length 15
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112)
	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349)
```

**Comment by ImeshaDilshani** [comment]
solved
